#!/usr/bin/env sh

# global settings
yabai -m config external_bar                main:24:0
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         autoraise
yabai -m config window_placement            second_child
yabai -m config window_opacity              off
yabai -m config window_opacity_duration     0.0
yabai -m config window_shadow               off
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off
yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# general space settings
yabai -m config layout                      bsp
yabai -m config top_padding                 12
yabai -m config bottom_padding              12
yabai -m config left_padding                12
yabai -m config right_padding               12
yabai -m config window_gap                  12
